version: '3'
services:
    ##
    # Battle Microservice
    ##
    microservice_battle_php:
        container_name: microservice_battle_php
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ./microservices/battle/app:/var/www/app:delegated
        expose:
          - 9003
          - 9000

    microservice_battle_nginx:
        container_name: microservice_battle_nginx
        build:
          context: .
          dockerfile: ./microservices/battle/nginx/Dockerfile
        volumes:
            - ./microservices/battle/app:/var/www/app:delegated
        depends_on:
            - microservice_battle_php
        ports:
            - 8443:443
            - 8081:80
    ##
    # Telemetry: prometheus
    ##
    telemetry:
      container_name: telemetry
      image: prom/prometheus:v2.36.1
      volumes:
        - ./telemetry/etc:/etc/prometheus/
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - "9999:9090"