# Creates a new secret with name, latitud, longitude, location_name
POST http://localhost:8083/api/v1/secrets
Content-Type: application/json

{
    "name": "zafer",
    "latitude":"1.23",
    "longitude":"-1.23",
    "location_name": "test"
}

###

# Returns a list of all secrets
GET http://localhost:8083/api/v1/secrets

###

# Retrieves a specific secret identified by the secret ID
GET http://localhost:8083/api/v1/secrets/1

###