scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservice_battle_nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['microservice_battle_nginx:8081']

  - job_name: 'microservice_user_nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['microservice_user_nginx:8084']
